authserviceUrl: abc
authserviceUrl1: def
name: Reading from QA config
db.datasourcename: java:comp/env/jdbc/domaAuthServiceDataSource
AUTHORITY: https://login.windows.net/
RCBO_GRAPH_URL: https://graph.windows.net/rcbo.org/me?api-version=1.6
#FISCAL Properties
FISCAL_TENANT_ID: rcbo.org
FISCAL_CLIENT_ID: e3ed5207-1763-4c3a-ae5e-f271ebd40d77
FISCAL_CLIENT_SECRET: L5V8wVjjK+HE0amr9eJ2YDPuEC7HTZtBY9OIwm+buqc=
FISCAL_GROUP_ID: 70af7cfd-dcbf-44c9-90c7-802fbea813ea
#CPAS Properties
CPAS_TENANT_ID: rcbo.org
CPAS_CLIENT_ID: 61a89a63-19e7-4855-b647-b03e586a4ad1
CPAS_CLIENT_SECRET: 64.Al4FVkX8SdscftBIcT.ArDqMplK._
CPAS_GROUP_ID: c7490ff8-f202-4d3e-b153-b59141a91bcf
#PAD Properties
PAD_TENANT_ID: rcbo.org
PAD_CLIENT_ID: e3ed5207-1763-4c3a-ae5e-f271ebd40d77
PAD_CLIENT_SECRET: L5V8wVjjK+HE0amr9eJ2YDPuEC7HTZtBY9OIwm+buqc=
PAD_GROUP_ID: 2ef1ef4c-27ac-4555-b61b-1465db9a9575
#COMMON Properties
TENANT_ID: rcbo.org
CLIENT_ID: e3ed5207-1763-4c3a-ae5e-f271ebd40d77
CLIENT_SECRET: L5V8wVjjK+HE0amr9eJ2YDPuEC7HTZtBY9OIwm+buqc=
#MASSCOUNT Properties
MASSCOUNT_GROUP_ID: e9ea2f42-84ad-4656-b06f-046374befc40
#MDS Properties
MDS_GROUP_ID: 6f4b9543-197a-4173-a5eb-dc5dae85557b
#CONSECRATED Properties
CONSECRATED_GROUP_ID: a217faad-48b8-402d-9bfc-d4556c73d130
#SEMINARIAN Properties
SEMINARIAN_GROUP_ID: f675e61b-3870-4fb0-9692-032261c206b1
#VOLUNTEER Properties
VOLUNTEER_GROUP_ID: 92bb7fb4-eef9-45ba-877d-0961a9da7746
#PRIEST Properties
PRIEST_GROUP_ID: 887a6761-0b6f-48c8-bdc4-180bf657554b
#CONTRACTORS Properties
CONTRACTORS_GROUP_ID: 3f636edc-4854-4e89-88f7-c2341e8978a0
#VOCATION Properties
VOCATION_GROUP_ID: 6f4b9543-197a-4173-a5eb-dc5dae85557b
#FINGERPRINT Properties
FINGERPRINT_GROUP_ID: 1a5e6045-80f1-42bf-b9d8-3495450217dd
#HR Properties
HR_GROUP_ID: e6aa05e9-422b-49ea-9632-e67cbc104a6e
